### ISSUE TITLE
Bomberman Quest: freezes when selecting Battle from menu

### ISSUE THREAD

**Issue by tjanas** [redacted173/sd2snes#1]
Firmware 1.10.3_sgb00
Regular SD2SNES
Freezes when selecting Battle. SGB2 menu is still responsive.

**Comment by redacted173** [comment]
Missing serial link completion interrupt.  It's hooked up in a recent commit.

**Comment by Goldanas** [comment]
As of SGB02, the game does not lock up when selecting Battle, it just makes a tone and nothing happens, which I think is possibly what the original did? Basically, no hard failure anymore.

**Comment by redacted173** [comment]
Fixed here: https://github.com/redacted173/sd2snes/releases/tag/sgb02
