### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by SHaMROCK73** [redacted173/sd2snes#10]
The game ALLEYWAY and BASEBALL both do not work...

**Comment by chmcarro** [comment]
What happens?

**Comment by SHaMROCK73** [comment]
On ALLEYWAY game starts but immediately goes in to "PAUSE" state and paddle goes directly to far left on the play field.  You can unpause, but you paddle will not move.

BASEBALL launches but no inputs will do anything.  SGB2 menu functions still work and you can use the SD2SNES functions to back out to the game list...

**Comment by SHaMROCK73** [comment]
OK, just downloaded the latest firmware and now both ALLEYWAY and BASEBALL are working...

Thanks guys...
