### ISSUE TITLE
In-Game Hooks Stop Working in Space Invaders Arcade Mode

### ISSUE THREAD

**Issue by Nam-Ereh-Won** [redacted173/sd2snes#11]
Space Invaders has a SNES port of the game built in that you can launch from Super Game Boy. In-Game Hooks work fine when you select the Super Game Boy mode upon start. If you go into Arcade mode hooks stop working once it's loaded the SNES port.

As far as I'm aware, this is the only title that contains and loads into memory a SNES title. It may be possible to catch the load and patch in the hooks, but I don't expect to see it get fixed. I was pleasantly surprised to know that it worked at all.

**Comment by redacted173** [comment]
The in-game hooks for SGB were rewritten to reduce the FPGA requirements, eliminate the overhead on games, and eliminate some cases of dropped inputs.  It was part of the new design to eliminate the SNES-side overhead of hooking into interrupts and unfortunately this is one of the known cases where the new design doesn't work.  The previous hack with the old in-game hooks used to crash space invaders arcade so having it run without needing to turn off the hooks is an improvement.

The old hook code is unlikely to make a come-back.  It won't fit on the SD2SNES classic.

**Comment by redacted173** [comment]
Marking as wontfix for now.  In the unlikely chance space opens up on SD2SNES classic other things will fill it before a custom hook for space invaders arcade.

SGB in game hooks will stop working whenever the sgb2_snes.bin code is replaced.  This can happen either by the user changing the file or the game replacing the code in the file which is what happens in this case.
