### ISSUE TITLE
Donkey Kong

### ISSUE THREAD

**Issue by ghost** [redacted173/sd2snes#12]
I've read about a bug posted on discord from a user called dampfwalze, who however has no git account, so I thought to report it:

Donkey Kong now has problems with the new sgb03.
The score line on the top of the screen flickers and when you play the first levels (original arcade levels), finish them and the short animation of Kong pressing himself trough the door, his “behind” appears in strange colors at the top of the screen.

**Comment by redacted173** [comment]
I don't see this with my current changes so it must have been fixed in: 7df543fc17dfd48ff7231cfc969f4c749c6e08e1

Someone can confirm in the next release.

**Comment by ghost** [comment]
That's great, if you don't mind, I keep you updated with the issues report that are talked about at discord (classic gaming -> sd2snes general):

There seems to be another problem a problem with space invaders:
Mr_Boo_Berry: Space Invaders - Stereo is reversed from what it should be (generally, this is the best game to test)
Ikari_01: hm, I just tested on sd2snes (sgb00 however) and the channels aren't reversed
yeah, they are swapped on sgb03 ^^

Btw, I am that guy that brought msu1 for sgb get rolling, and thanks to your sgb-sd2snes code the current developed 2 games are fully working in msu1 for sd2snes (in case you don't know yet :) ):
FFA: https://www.zeldix.net/t2049-adventures-of-mana-seiken-densetsu-i-final-fantasy-adventuremystic-quest-for-sgb
LADX: https://www.zeldix.net/t2115-link-s-awakening-super-gameboy-msu-1
Georgeous work, congratulations!!!

**Comment by mrehkopf** [comment]
I'm in favor of opening an extra issue for that which makes it possible to track them individually.

**Comment by redacted173** [comment]
I updated the separate bug regarding the audio channels being swapped.

Hopefully the MSU audio can be retained for SD2SNES classic, but right now it's not looking good.

**Comment by redacted173** [comment]
Fixed in sgb04:

https://github.com/redacted173/sd2snes/releases/tag/sgb04
