### ISSUE TITLE
Urusei Yatsura: Miss Tomobiki o Chigase! (J)

### ISSUE THREAD

**Issue by Nigoli** [redacted173/sd2snes#15]
The game and it's translation won't go past it's trademark screen.

Tested on SD2SNES Pro SGB04.

Thank you.

**Comment by redacted173** [comment]
It's doing a DMA from VRAM which leaves the system bus available.  Support for this was missing.  Should be fixed in this commit:

a0d7627af036cb9eb2f0b6fd6df50b91ede42308

**Comment by rhythm-g** [comment]
I can confirm that this has been fixed on my SD2SNES rev. F in the sgb05 release.

**Comment by Nigoli** [comment]
I can also confirm it working on SD2SNES Pro for sgb05.

@redacted173 Thank you for the fix.
@rhythm-g Thank you for testing.
