### ISSUE TITLE
Sd2SNES USB+Savestates

### ISSUE THREAD

**Issue by B-u-R-n-I-n-G-f-I-r-E** [redacted173/sd2snes#17]
Hello,
could You make a version with savestate support (SNES games only) and
USB support (also for SNES games only) like this firmware https://github.com/furious/sd2snes/releases/tag/v1.10.3
?

**Comment by therourke** [comment]
Has this been included in the latest release? It's not entirely clear from the release notes

**Comment by therourke** [comment]
OK. Did some of my own testing and see that SGB support isn't compatible with [SD2SNES 1.10.3-frs-v11 (Unofficial)](https://github.com/furious/sd2snes/releases) firmware save states. Any reason these two things can't live in harmony?

**Comment by redacted173** [comment]
This repo was only for developing SGB support.  Looks like some other people are working on integrating it with other features.
