### ISSUE TITLE
Save Game Boy games as .sav instead of .srm?

### ISSUE THREAD

**Issue by ABOhiccups** [redacted173/sd2snes#18]
Can you make Game Boy games save as .sav file instead of .srm file on SD2SNES/FXPAK SD Card?

**Comment by symbios24** [comment]
As far as i know only the emulators make sav files

**Comment by redacted173** [comment]
Emulators seem to be all over the place with the extension and where they put the files.  I'll leave it up to people integrating the SGB support to decide these things.
