### ISSUE TITLE
Super Gameboy Bios

### ISSUE THREAD

**Issue by symbios24** [redacted173/sd2snes#19]
Hello, is it possible to add inside the Super Gameboy Bios rom a gameboy rom/game??
So when you run the bios it will load the rom/game??
For people that have the super everdrive like me and can't afford to buy Sd2Snes ??

Thanks

**Comment by nadiaholmquist** [comment]
The Super Game Boy cartridge actually contains the hardware of the Game Boy, it's not based on emulation, as the SNES is not powerful enough to do that.

**Comment by jensma** [comment]
I think this is possible. Just give me a day or two and I'll implement it.

**Comment by nadiaholmquist** [comment]
It's not. Sure you could bundle the game and BIOS in some way and add support for that on the sd2snes, but Game Boy games will never play without hardware support as the Super Game Boy is not an emulator and requires special cartridge hardware to work.

**Comment by jensma** [comment]
> It's not. Sure you could bundle the game and BIOS in some way and add support for that on the sd2snes, but Game Boy games will never play without hardware support as the Super Game Boy is not an emulator and requires special cartridge hardware to work.

Nah, I'm already halfway done

**Comment by nadiaholmquist** [comment]
Don't waste your time, this is not gonna happen. It's simply not possible.

**Comment by jensma** [comment]
> Don't waste your time, this is not gonna happen. It's simply not possible.

Uhm, I'm already loading and starting games without any issues. :D

**Comment by nadiaholmquist** [comment]
On what hardware?

**Comment by jensma** [comment]
> On what hardware?

Latest sd2snes revision, PAL SNES without any modifications

**Comment by nadiaholmquist** [comment]
Well yeah, if you're running the SGB firmware on that it's gonna work, but this will never work on an EverDrive as the original poster asked about.

**Comment by jensma** [comment]
oh
