### ISSUE TITLE
Bug: Flickering row of pixels in Bomberman GB (USA)

### ISSUE THREAD

**Issue by mac-a-r0ni** [redacted173/sd2snes#20]
When playing Bomberman GB in the bottom right of the screen during gameplay a row of pixels flicker consistently. Tested on a real sgb2 with an everdrive and this does not happen on hardware.

To reproduce, pick standard game and choose left game option (likely does the same on either) and play the first map.

**Comment by redacted173** [comment]
The SGB enhanced version tells the SNES to poll 4 controllers which seems to cause timing problems for the SNES DMA'ing GB scanline 120.  An early notification of a scanline and row buffer written is now available to the SNES to give it some extra time.  The problem should be improved but probably not completely eliminated in this commit:

https://github.com/redacted173/sd2snes/commit/a5c15656187063ab7bf622ef5cd30c6da9a5eeaa

Most SGB enhanced games probably don't have all 4 controllers enabled.

**Comment by redacted173** [comment]
Fixed in sgb07.  May not be perfect, though, as it seemed to be a race between the bios and SGB ICD2/PPU.
