### ISSUE TITLE
Thank you redacted173, much appreciated

### ISSUE THREAD

**Issue by terminator2k2** [redacted173/sd2snes#21]
Didnt know how how to contact you, so leaving this here, can delete if you want, but would like to say a very BIG THANK YOU, for all your time and effort  for bringing Super Gameboy to the sd2snes/Fx pak...... 👍 

now when you get a spare 5 minutes how about a cheeky request of porting spc7110 from the mister project to SD2snes 🥇 

Thank you...!!!!!!!

**Comment by redacted173** [comment]
No problem.  I'm happy that people are enjoying it.
