### ISSUE TITLE
FXPAK PRO supported I think...

### ISSUE THREAD

**Issue by edrozenberg** [redacted173/sd2snes#25]
Assume I would use the `.im3` and `.bi3` files on the FXPAK PRO (FXPAK is the new name for SD2SNES). Haven't tried it yet.

**Comment by redacted173** [comment]
I believe the SD2SNES Pro and FXPak Pro are currently the same and are supported.  Here are the files listed in readme.txt:

  /sd2snes/firmware.img  # SD2SNES Classic
  /sd2snes/fpga_sgb.bit  # SD2SNES Classic
  /sd2snes/fpga_sgb_msu.bit # SD2SNES Classic
  /sd2snes/firmware.im3  # SD2SNES Pro
  /sd2snes/fpga_sgb.bi3  # SD2SNES Pro
