### ISSUE TITLE
Corrupted palette on Megami Tensei Last Bible II

### ISSUE THREAD

**Issue by jz-k** [redacted173/sd2snes#27]
The SGB-enhanced palette seems corrupted on this game. Switching to the non-enhanced palette makes the game playable. The broken visuals should be obvious as soon as the title screen appears, and never go away (unless as mentioned, you swap palettes).

**Comment by redacted173** [comment]
I don't see any problems in the untranslated version of MTG-LB2 SHA-1: 84DF9508BDD8B24DFB19A74744FEC492FFFEE56D

But the translated version shows a checkerboard-like blue/black/green background inside the GB content.
"[T-En by EsperKnight v1.0]" SHA-1: 6F2BA0DE137CFC3BE136F6477DD84873663745A0

![mtg-lb2-sgb](https://user-images.githubusercontent.com/67377137/114308010-2a93ca80-9a97-11eb-83bf-9ed8b2f89287.PNG)

The same background problem shows up on an original SGB2 and mesen-s 0.4.0.  So this looks like a bug with the translation assuming it's the one you are using.  Perhaps the title screen tile changes the translation made don't account for SGB-enhanced content?  I didn't look into it in detail to know the exact source of the bug.  You'll have to find someone to fix the hack if you'd like to play with the SGB palette without the problem.

**Comment by jz-k** [comment]
Thanks for digging. You’re totally right. Tested this after raising the issue. I see what you see.
