### ISSUE TITLE
SGB, joystick commands don't work.

### ISSUE THREAD

**Issue by Gods69** [redacted173/sd2snes#30]
Hello,
I'm running the sd2snes_firmware_v1.11.0b1 on a Chine SD2SNES (PRO) card and when i run one GB game it run well on a SGB2 screen but i can not play it, the joystick controls are not working. The card is the latest version (11/2021) and it use the XC3S400 FPGA chip.
Thank You.

**Comment by redacted173** [comment]
Hi.

What type of SNES (original NTSC/PAL 2/1/3 etc, SuperNT, clone) are you using?

What type of controller are you using?  What port is it plugged into?  Are you using a multitap?

Have you tried the older release sgb07?  https://github.com/redacted173/sd2snes/releases/tag/sgb07

Can you activate the Super GameBoy menu by pressing L+R?  This menu runs on the SNES like a normal game and not on the SGB.

If the menu doesn't activate then it there is likely something wrong with how the SNES SGB ROM is running on your console.  The way the controller is supposed to work is the SNES reads them and then writes a copy to the SGB.  You may need to use a different controller or console to fix this as the SGB can't solve it.

If the menu doesn't work some other suggestions are:
- make sure you are running NTSC
- try a different controller
- disable all in-game hooks in the menu (this shouldn't affect anything unless they were changed in 1.11.0b1)
- try sgb07
- try a different SNES

I also don't know how your particular SD2SNES works or if the SGB implementation was modified.  If it has some incompatible pinout on the FPGA that could cause problems.  You may need to contact the people who made your SD2SNES to see if SGB is compatible and expected to work.

**Comment by Gods69** [comment]
Fixed! Strange issue. It was the controller... I'm using one SNES controller clone. (new and woking well with SNES games). I switched with another one, also clone but different brand and GB games work now. 
( i'm running on original SNES PAL console, CPU-->2, PPU1-->1 and PPU2-->3 )

**Comment by redacted173** [comment]
Thanks for the update.  I also have a controller that doesn't work on both the original SGB2 and SD2SNES SGB.  The SGB's SNES ROM that is capturing joystick input, copying the video from SGB to SNES output, and drawing the menus is pretty timing sensitive.  Controllers that don't like the way the input is read (or the time it is read) and any changes in SNES CPU timing such as running at PAL speeds can cause it to fail.  If the menu doesn't come up with L+R, which doesn't execute any code on the SGB, it's generally a problem with some combination of the controller or console.  The same controller and console may work fine in other SNES games.
