### ISSUE TITLE
Broken music in Prehistorik Man

### ISSUE THREAD

**Issue by nadiaholmquist** [redacted173/sd2snes#4]
In Prehistorik Man, the notes in the music don't end as they should, and keep going until something else is played on that channel. This is basically the opposite issue of how the game's music is broken on early Game Boy Color models.

**Comment by redacted173** [comment]
This was using an envelope register write side effect to wrap the volume from 0xF to 0x0.  Some of these side effects are implemented in this commit:

55f409c0686b659a40a6e64f1b9cba122f220339

**Comment by redacted173** [comment]
Fixed here: https://github.com/redacted173/sd2snes/releases/tag/sgb02
