### ISSUE TITLE
Alleyway (GB) compatibility issues

### ISSUE THREAD

**Issue by chmcarro** [redacted173/sd2snes#5]
Alleyway, this is an original Game Boy game that Nintendo advertised specifically with the SGB with a default color scheme. This is a Breakout style game; however, with the sd2snes firmware, I am experiencing what appears to be a defect in which the game auto pauses upon loading the level and the bumper bar is fixed to the left of the screen. Perhaps others may be able to reproduce this problem to confirm the defect?

**Comment by redacted173** [comment]
Can't reproduce this on Alleyway (32KB, CRC-32 5CC01586).  Make sure you have a working ROM.  Also try testing on an original SNES console and controller if you aren't already.

**Comment by chmcarro** [comment]
We have matching ROM CRC-32. I'm testing on my US launch SNES CPU 1/1/1 with original controller. Other GB games working just fine with your sgb01 release, but this one loads the intro just fine, but once the level is entered, it is as if a "start button" trigger is initiated and the pad moved instantly to the far left. I can unpause, but cannot move the pad to the right.  ROM works fine for me on visualboyadvance.

**Comment by chmcarro** [comment]
I've had previous issues with CPU 1/1/1 compatibility if there's some memory access violation. You are probably familiar with this already, but for visibility:

https://forums.nesdev.com/viewtopic.php?t=14196

Would this be at play with your SGB core?

**Comment by Goldanas** [comment]
Using the sgb02 release, an SD2SNES Pro, and a 2/1/3 SNES, there does not appear to be an issue with this game for me. I didn't check on the previous release, though, but it still couldn't hurt for you to check on this latest release and see if that clears things up for you.

**Comment by chmcarro** [comment]
Confirmed fixed with sgb02

**Comment by SHaMROCK73** [comment]
I have the same issue and it has not been fixed with the update

**Comment by chmcarro** [comment]
new report that is still outstanding for some. @SHaMROCK73 what CPU do you have? This was fixed on my 1/1/1

**Comment by SHaMROCK73** [comment]
Do you mean the CPI of the SNES?  What is 1/1/1?  What about BASEBALL, does it work for you?

**Comment by dreimer1986** [comment]
We mean that: https://user-images.githubusercontent.com/11965591/42722791-d0b5a628-8752-11e8-98f8-590522063e15.JPG the 3 numbers below.

**Comment by SHaMROCK73** [comment]
![IMG_20200708_120951185](https://user-images.githubusercontent.com/30869614/86944070-3c65cd00-c115-11ea-9f1e-218ea32f1e97.jpg)

So 2/1/3

**Comment by Goldanas** [comment]
You're not on the latest SGB release. You should try the sgb02 release from here: https://github.com/redacted173/sd2snes/releases

**Comment by SHaMROCK73** [comment]
What the hell?  I downloaded the updated "care package" from Smokemonster...

**Comment by SHaMROCK73** [comment]
OK, just downloaded the latest firmware and now both ALLEYWAY and BASEBALL are working...

Thanks guys...

**Comment by chmcarro** [comment]
> 
> 
> What the hell? I downloaded the updated "care package" from Smokemonster...

The care package was updated 7/3 and matches the sgb02 files

**Comment by SHaMROCK73** [comment]
Well I guess I was too early, or something...
