### ISSUE TITLE
SGB01 Changelog clarification

### ISSUE THREAD

**Issue by chmcarro** [redacted173/sd2snes#7]
Apologies in advance if this is not the appropriate spot for this discussion as this is no less an issue and more a discussion for clarification on some of the changes:

"Addresses window graphics problems with CAW bosses and likely many other games."
What is "CAW"?

"Changed SD2SNES classic to only load MSU bit file for enabled ROMs to make development easier. The MSU bit file may lag in development."
What's the difference in features between Classic and Pro for SGB?

**Comment by chmcarro** [comment]
I'd like to solve the puzzle... "Contra: The Alien Wars (Game Boy)" boss battles. Is that right?

As for the 2nd discussion, looking for clarity/confirmation the FPGA on the SD2SNES classic vs pro feature set as it relates to SGB, MSU-1 hacks, save states, etc.

**Comment by redacted173** [comment]
Yes.  Contra Alien Wars.

There isn't a feature list.  We'll have to wait and see what fits and makes sense to include.  At 95-97% logic utilization and borderline timing the SD2SNES classic resources are nearly exhausted in the current implementation.

**Comment by chmcarro** [comment]
Thanks!
