### ISSUE TITLE
Bomberman Collection (GB) loads back to the main menu when selecting games

### ISSUE THREAD

**Issue by Goldanas** [redacted173/sd2snes#8]
This is a Japanese collection of Bomber Boy, Bomber Man GB 1, and Bomber Man GB 2. It has Super Game Boy menu support, and should include the normal bonus features they had outside the collection. The total ROM image size is pretty large encapsulating all the games.

The game boots to a title screen with custom SGB background art, and lets you pick from the 3 games. Selecting any of them reloads the main menu, including the special background art (like it was going to load the game specific art, but then thought better of it).

**Comment by Goldanas** [comment]
Same thing also happens in "Mortal Kombat & Mortal Kombar II", which is also a collection of those GB games by the same individual names. It has a similar title screen, is about the same ROM size, and selecting them boots right back to that same screen, though much more immediately, because it doesn't have any SGB support for backgrounds.

I guess it may be an issue with this type of packaging or something. I can say that this doesn't happen on the Konami Collections, but perhaps those are built differently.

**Comment by redacted173** [comment]
The following commit adds MBC1M support since it doesn't require a lot of FPGA resources.  The detection is a hack, but it's not obvious if there is a better way to do it.  The remaining unsupported mappers are unlikely to be added any time soon or at all.

54efd3958d85f3102b1075421221721f71b51f21

**Comment by Goldanas** [comment]
I can confirm the issue is addressed for the two reported games, possibly more, in SGB02.
