### ISSUE TITLE
Super Mario RPG (SNES) has graphical issues on SD2SNES Pro on 2/1/3 SNES (possibly 1chip)

### ISSUE THREAD

**Issue by Goldanas** [redacted173/sd2snes#9]
![20191114_220827_HDR](https://user-images.githubusercontent.com/67668858/86195307-6b70b300-bb05-11ea-9dbf-92da0395f7fe.jpg)

Random graphical artifacts like those in the picture can appear in the world environment. They don't always appear, and they don't always appear in the same place (so they do seemingly have somewhat random and errant behavior). An easy way to spawn them in is to press X and go to the menu and then exit the menu, change place, and then repeat to see if they show. They seem almost random, but they might be based on your screen position and when it loads the background and how.

If you're familiar with the game, you'll notice them appearing about 50 percent of the time, sometimes online 1 or 2, and sometimes as many as 10.

I have a real original SMRPG cart, and these artifacts do not appear when playing on that cart. This is an issue in the official firmware as well, but worth tracking.

**Comment by nadiaholmquist** [comment]
This is the repo for the Super Game Boy firmware, try posting your issue on [the main repo](https://github.com/mrehkopf/sd2snes) instead.

**Comment by Goldanas** [comment]
Will do.
